#!/bin/bash

set -e

if [ ! -f .env ]; then
  cp .env.defaults .env
  echo "Please edit the .env file I just copied from .env.defaults!"
  exit 1
fi
set -a
source .env >/dev/null 2>&1
V1_DATABASE_URL="$V1_DATABASE_URL"
if [ "$V1_DATABASE_URL" == "" ]; then
  V1_DATABASE_URL="postgres://postgres:$V1_DB_PASSWORD@v1-db/postgres"
fi
V2_DATABASE_URL="$V2_DATABASE_URL"
if [ "$V2_DATABASE_URL" == "" ]; then
  V2_DATABASE_URL="postgres://postgres:$V2_DB_PASSWORD@v2-db/postgres"
fi
set +a

COMMAND="$1"

if [ -f "./commands/$1.sh" ]; then
  bash "./commands/$1.sh" $2 $3 $4 $5
else
  docker-compose $*
fi
