#!/bin/bash

set -e

if [ ! -f .env ]; then
  cp .env.defaults .env
  echo "Please edit the .env file I just copied from .env.defaults!"
  exit 1
fi
set -a
source .env >/dev/null 2>&1
set +a

COMMAND="$1"

if [ -f "./commands/$1.sh" ]; then
  bash "./commands/$1.sh" $2 $3 $4 $5
else
  docker-compose $*
fi
